name: Deploy Site

on:
  push:
    branches: [ mainline ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload to Porkbun
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: pixie-ftp.porkbun.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          dangerous-clean-slate: true
